// ============================================================
//  MODEL: packages.model.js
//  Defines all package tiers, features, and pricing bands.
//  This is pure data — no React dependencies.
// ============================================================

export const PACKAGES = [
  {
    id: 'basic',
    name: 'Basic',
    tagline: 'A Beautiful Beginning',
    priceRange: { min: 400000, max: 600000 },
    displayPrice: '₹4 – 6 Lakhs',
    color: '#6366F1',
    gradient: 'linear-gradient(135deg,#4F46E5,#7C3AED)',
    popular: false,
    icon: '💐',
    includes: [
      'Basic venue decoration',
      'Standard photography (1 photographer)',
      'Buffet catering (up to 100 guests)',
      'Basic floral arrangements',
      'Event coordination (1 day)',
      'Invitation design (digital)',
    ],
    excludes: [
      'Videography',
      'Pre-wedding shoot',
      'DJ & entertainment',
      'Drone footage',
      'Accommodation',
      'Destination options',
    ],
  },
  {
    id: 'medium',
    name: 'Medium',
    tagline: 'Elegance Redefined',
    priceRange: { min: 1000000, max: 1500000 },
    displayPrice: '₹10 – 15 Lakhs',
    color: '#7C3AED',
    gradient: 'linear-gradient(135deg,#7C3AED,#9333EA)',
    popular: true,
    icon: '💍',
    includes: [
      'Themed venue decoration',
      'Photography & videography',
      'Pre-wedding shoot (local)',
      'Multi-cuisine catering (up to 200 guests)',
      'DJ & sound system',
      'Floral centrepieces & mandap',
      'Event coordination (2 days)',
      'Printed invitations',
    ],
    excludes: [
      'Drone footage',
      'Destination shoot',
      'Accommodation',
      'Live performers',
      'Cinematic video production',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    tagline: 'Pure Luxury, No Compromise',
    priceRange: { min: 2500000, max: 3000000 },
    displayPrice: '₹25 – 30 Lakhs',
    color: '#9333EA',
    gradient: 'linear-gradient(135deg,#9333EA,#D4AF37)',
    popular: false,
    icon: '👑',
    includes: [
      'Luxury venue with premium décor',
      'Drone shoot & cinematic video',
      'Pre-wedding shoot (premium location)',
      'Fine-dining catering (up to 400 guests)',
      'Full entertainment setup (DJ + live band)',
      'Makeup & styling for couple',
      'Coordinated transportation',
      'Event coordination (3 days)',
      'Designer invitations',
      'Photo album & highlights reel',
    ],
    excludes: [
      'Destination wedding setup',
      'International accommodation',
      'International pre-wedding shoot',
    ],
  },
  {
    id: 'luxury',
    name: 'Luxury',
    tagline: 'Destination Dreams, Delivered',
    priceRange: { min: 4000000, max: null },
    displayPrice: '₹40 Lakhs+',
    color: '#D4AF37',
    gradient: 'linear-gradient(135deg,#D4AF37,#F0D060)',
    popular: false,
    icon: '✨',
    includes: [
      'Destination wedding (anywhere in India)',
      'Luxury 5-star venue & accommodation',
      'International/destination pre-wedding shoot',
      'Full cinematic production team',
      'Celebrity-style makeup & styling',
      'Gourmet multi-day catering (unlimited guests)',
      'Full entertainment (DJ + live acts + fireworks)',
      'Dedicated wedding planner',
      'Guest transportation & hospitality',
      'Custom printed & digital invitations',
      'Drone + aerial photography',
      'Premium photo books & films',
    ],
    excludes: [],
  },
]

export const PACKAGE_COMPARISON_FEATURES = [
  'Venue Decoration',
  'Photography',
  'Videography',
  'Pre-wedding Shoot',
  'Drone Footage',
  'Catering',
  'DJ / Entertainment',
  'Makeup & Styling',
  'Transportation',
  'Accommodation',
]

export const PACKAGE_FEATURE_MATRIX = {
  basic:   ['Basic', '1 Photographer', '✗', '✗', '✗', 'Up to 100', '✗', '✗', '✗', '✗'],
  medium:  ['Themed', 'Photo + Video', 'Standard', 'Local', '✗', 'Up to 200', 'DJ', '✗', '✗', '✗'],
  premium: ['Luxury', 'Professional', 'Cinematic', 'Premium Location', '✓', 'Up to 400', 'DJ + Band', 'Couple', 'Coordinated', '✗'],
  luxury:  ['Destination Premium', 'Full Team', 'Cinematic 4K', 'Destination', '✓ Aerial', 'Unlimited', 'DJ + Live Acts', 'Full Team', 'Full Fleet', '5-Star'],
}
